is_dnn: false

data:
  eval_dt: 1  
  root: "<ruta_del_conjunto_de_datos>"
  dataset: "E-NAVI"
  sequence: "<nombre de la secuencia>"
  height: 480
  width: 640
  load_gt_flow: False
  gt: ""
  n_events_per_batch: 100000
  ind1: 1030000
  ind2: 1080000
  offset: 0

output:
  output_dir: "<ruta_para_el_resultado>"
  show_interactive_result: False

solver:
  method: "pyramidal_patch_contrast_maximization"
  time_aware: False
  # time_bin: 10
  # flow_interpolation: "burgers"
  # t0_flow_location: "middle"
  patch:
    # initialize: "random"
    initialize: "global-best"
    # initialize: "grid-best"
    scale: 5
    crop_height: 480
    crop_width: 640
    filter_type: "bilinear"
  motion_model: "2d-translation"
  warp_direction: "first"
  parameters:
    - "trans_x"
    - "trans_y"
  cost: "hybrid"
  outer_padding: 0
  cost_with_weight:
    multi_focal_normalized_gradient_magnitude: 1.
    total_variation: 0.01
  iwe:
    method: "bilinear_vote"
    blur_sigma: 1

optimizer:
  n_iter: 40
  method: "Newton-CG"
  max_iter: 25
  parameters:
    trans_x:
      min: -150
      max: 150
    trans_y:
      min: -150
      max: 150
